### ISSUE TITLE
Maven URL has changed

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/maven-cms-plugin#1]
http://repo.enonic.com/maven returns 404

http://repo.enonic.com/public is probably the correct URL?

**Comment by jsi** [comment]
Hei Jonas!
Takk for tipset!  Det er vel bare README fila du refererer til?  Det var bare der jeg fant den, og det forklarer vel hvorfor dette ikke har blitt oppdaget før!  😜
Fikset nå!
